### ISSUE TITLE
Error with code

### ISSUE THREAD

**Issue by loiclosson** [dominicplouffe/HorseRacingPrediction#2]
Hi, I just try your code and I got this error, do you have an idea to correct it ? 

`INFO:root:Training Finish Position
Traceback (most recent call last):
  File "trainer.py", line 160, in <module>
    trn.train()
  File "trainer.py", line 44, in train
    X, y, = self._get_data('training-2016-12-01-2017-02-28.csv')
  File "trainer.py", line 25, in _get_data
    for i, row in enumerate(training_data):
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`

**Comment by loiclosson** [comment]
Ok I correct it, I change rb in rt !
